apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-localhost-root
  namespace: cert-manager
spec:
  isCA: true
  commonName: dev-localhost-root
  secretName: dev-localhost-root
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dev-localhost-issuer
spec:
  ca:
    secretName: dev-localhost-root
